/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */

public class AdminRegistration extends javax.swing.JFrame
{
    private DefaultTableModel adminDetails = new DefaultTableModel();
    private String column [] = {"UserID", "Username", "Email", "Phone Number"};
    
    

    /**
     * Creates new form AdminRegistration
     * @throws java.io.IOException
     */
    public AdminRegistration(String adminUserID) throws IOException 
    {
        initComponents();
        this.adminUserID=adminUserID;
        adminDetails.setColumnIdentifiers(column);
        loadDetails();
    }
    
    public AdminRegistration()
    {
        initComponents();
        adminDetails.setColumnIdentifiers(column);
        loadDetails();
    }
    
    private String adminUserID;
    private String selectedUserID;
    private String adminID;
    
    public void loadDetails() 
    {
        Registration rA = new Registration();
        adminDetails.setRowCount(0); // Clear existing rows

        try 
        {
            List<Admin> adminList = rA.readAdmin();
            for (Admin am : adminList) 
            {
                Object[] rowData = 
                {
                    am.getAdminUserID(),
                    am.getAdminUsername(),
                    am.getEmail(),
                    am.getPhoneNumber(),
                };
                adminDetails.addRow(rowData);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
   
    
    public void displayPassword(String adminUserID) 
    {
        Registration rA = new Registration();

        try 
        {
            List<User> userList = rA.readUser();

            for (User user : userList) 
            {
                if (adminUserID.equals(user.getUserID())) 
                {
                    jTextFieldAPw.setText(user.getPassword());
                    break;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    
    
    private User getUserForAdminUserID(String adminUserID) 
    {
        Registration rA = new Registration();
        
        try 
        {
            List<User> userList = rA.readUser();

            for (User user : userList) 
            {
                if (user.getUserID().equals(adminUserID)) 
                {
                    return user;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAID = new javax.swing.JTextField();
        jTextFieldAUN = new javax.swing.JTextField();
        jTextFieldAPw = new javax.swing.JTextField();
        jTextFieldAEm = new javax.swing.JTextField();
        jTextFieldAPN = new javax.swing.JTextField();
        jButtonAC = new javax.swing.JButton();
        jButtonAE = new javax.swing.JButton();
        jButtonAD = new javax.swing.JButton();
        jButtonABTHP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableA = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("Admin");

        jLabel2.setText("UserID : ");

        jLabel3.setText("Username : ");

        jLabel4.setText("Password : ");

        jLabel5.setText("Email : ");

        jLabel6.setText("Phone Number : ");

        jButtonAC.setText("Create");
        jButtonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACActionPerformed(evt);
            }
        });

        jButtonAE.setText("Edit");
        jButtonAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAEActionPerformed(evt);
            }
        });

        jButtonAD.setText("Delete");
        jButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADActionPerformed(evt);
            }
        });

        jButtonABTHP.setText("Back To Home Page");
        jButtonABTHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonABTHPActionPerformed(evt);
            }
        });

        jTableA.setModel(adminDetails);
        jTableA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableAMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAC)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAUN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAPw, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAEm, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAPN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAD)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButtonABTHP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldAID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldAUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldAPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldAEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldAPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAE)
                    .addComponent(jButtonAD)
                    .addComponent(jButtonAC)
                    .addComponent(jButtonABTHP))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonABTHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonABTHPActionPerformed
        AdminHomePage hp1 = new AdminHomePage(adminUserID);
        hp1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonABTHPActionPerformed

    private void jButtonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonACActionPerformed
        String adminUserID = jTextFieldAID.getText();
        String adminUsername = jTextFieldAUN.getText();
        String password = jTextFieldAPw.getText();
        String email = jTextFieldAEm.getText();
        String phoneNumber = jTextFieldAPN.getText();
        
        Registration ra = new Registration();
        
        Admin nA = null;
        try {
            nA = ra.registerAdmin(adminUserID, adminUsername, password, email, phoneNumber);
        } catch (IOException ex) {
            Logger.getLogger(AdminRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object[] rowData = 
        {
            nA.getAdminUserID(), 
            nA.getAdminUsername(),
            nA.getEmail(), 
            nA.getPhoneNumber()
        };
        adminDetails.addRow(rowData);

        clearTextField();
    }//GEN-LAST:event_jButtonACActionPerformed

    private void jTableAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAMouseReleased
        int row = jTableA.getSelectedRow();

        String adminUserID = String.valueOf(adminDetails.getValueAt(row,0));
        
        displayPassword(adminUserID);
        
        User selectedUser = getUserForAdminUserID(adminUserID);
        
        String adminUsername = String.valueOf(adminDetails.getValueAt(row,1));
        String email = String.valueOf(adminDetails.getValueAt(row,2));
        String phoneNumber = String.valueOf(adminDetails.getValueAt(row,3));
        
        jTextFieldAID.setText(adminUserID);
        jTextFieldAUN.setText(adminUsername);
        jTextFieldAEm.setText(email);
        jTextFieldAPN.setText(phoneNumber);

    }//GEN-LAST:event_jTableAMouseReleased

    private void jButtonAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAEActionPerformed
        int row = jTableA.getSelectedRow();

        if (row == -1) {
        // No row selected, show an error or return
            return;
        }
        
        String selectedUserID = jTextFieldAID.getText();
        String newEmail = jTextFieldAEm.getText();
        String newPhoneNumber = jTextFieldAPN.getText();
        
        Registration ea = new Registration();
        
        DefaultTableModel adminDetails = (DefaultTableModel) jTableA.getModel();
        adminDetails.setValueAt(newEmail, row, 2);
        adminDetails.setValueAt(newPhoneNumber, row, 3);
        
        try {
            ea.editAdmin(selectedUserID, newEmail, newPhoneNumber);
        }catch (IOException e) {
            e.printStackTrace(); // Handle the exception according to your application's needs
        }
        
        clearTextField();

    }//GEN-LAST:event_jButtonAEActionPerformed

    private void jButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADActionPerformed
        int row = jTableA.getSelectedRow();
        Registration da = new Registration();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(this, "Please select a row");
        }
        else
        {
            String selectedUserID = String.valueOf(adminDetails.getValueAt(row, 0));
            
            try 
            {
                da.deleteAdmin(selectedUserID);
            } catch (IOException e) {
                e.printStackTrace(); // Handle the exception according to your application's needs
            }
            
            adminDetails.removeRow(row);
            clearTextField();
        }

    }//GEN-LAST:event_jButtonADActionPerformed

    public void clearTextField()
    {
        jTextFieldAID.setText("");
        jTextFieldAUN.setText("");
        jTextFieldAPw.setText("");
        jTextFieldAEm.setText("");
        jTextFieldAPN.setText("");
        
        Registration rca = new Registration();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegistration().setVisible(true);
            }  
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonABTHP;
    private javax.swing.JButton jButtonAC;
    private javax.swing.JButton jButtonAD;
    private javax.swing.JButton jButtonAE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableA;
    private javax.swing.JTextField jTextFieldAEm;
    private javax.swing.JTextField jTextFieldAID;
    private javax.swing.JTextField jTextFieldAPN;
    private javax.swing.JTextField jTextFieldAPw;
    private javax.swing.JTextField jTextFieldAUN;
    // End of variables declaration//GEN-END:variables
}
