/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fos;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANNABEL
 */
public class JFramePendingOrder extends javax.swing.JFrame {

    private DefaultTableModel model=new DefaultTableModel();
  
    private String column[]={"OrderID","Date", "Price","Service","ItemName","Order Status","ItemID"};
    private int row=-1;
    
    public JFramePendingOrder() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public JFramePendingOrder(String vendorid) 
    {
        initComponents();
        setLocationRelativeTo(null);
        this.vendorid=vendorid;
        model.setColumnIdentifiers(column);
        showtabledata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();
        lblshoworderid = new javax.swing.JLabel();
        lblshowName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Order");

        btnOrder.setText("Back to Order Page");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        ordertable.setModel(model);
        ordertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ordertableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(ordertable);
        if (ordertable.getColumnModel().getColumnCount() > 0) {
            ordertable.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            ordertable.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            ordertable.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            ordertable.getColumnModel().getColumn(3).setHeaderValue("Title 4");
            ordertable.getColumnModel().getColumn(4).setHeaderValue("Title 5");
            ordertable.getColumnModel().getColumn(5).setHeaderValue("Title 6");
            ordertable.getColumnModel().getColumn(6).setHeaderValue("Title 7");
            ordertable.getColumnModel().getColumn(7).setHeaderValue("Title 8");
            ordertable.getColumnModel().getColumn(8).setHeaderValue("Title 9");
            ordertable.getColumnModel().getColumn(9).setHeaderValue("Title 10");
            ordertable.getColumnModel().getColumn(10).setHeaderValue("Title 11");
        }

        jLabel1.setText("Order ID: ");

        btnAccept.setText("Accept Order");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnDecline.setText("Decline Order");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        jLabel2.setText("Item name: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(lblshoworderid, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnAccept)
                        .addGap(27, 27, 27)
                        .addComponent(btnDecline)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(btnOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblshowName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblshoworderid, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblshowName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecline)
                    .addComponent(btnAccept))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrder)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        JFrameOrder o1=new JFrameOrder(vendorid);
        o1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void ordertableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordertableMouseReleased
        // TODO add your handling code here:
        row=ordertable.getSelectedRow();
        String oid=String.valueOf(model.getValueAt(row, 0));
        String iname=String.valueOf(model.getValueAt(row, 4));
        lblshoworderid.setText(oid);
        lblshowName.setText(iname);
    }//GEN-LAST:event_ordertableMouseReleased

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        if(row==-1)
        {
            JOptionPane.showMessageDialog(this,"Please select a row");
        }else
        {
            try {
                int oid=Integer.parseInt(lblshoworderid.getText());
                Vorder ods=new Vorder();
                ods.receiveOrder(oid,"accepted");
                lblshoworderid.setText("");
                lblshowName.setText("");
                JOptionPane.showMessageDialog(rootPane,"OrderAccepted. Please refer to \"Order Accepted Page\".");
                model.removeRow(row);
                row=-1;
            } catch (IOException ex) {
                Logger.getLogger(JFramePendingOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
        if(row==-1)
        {
            JOptionPane.showMessageDialog(this,"Please select a row");
        }else
        {
            try {
                int oid=Integer.parseInt(lblshoworderid.getText());
                Vorder ods=new Vorder();
                ods.receiveOrder(oid,"declined");
                lblshoworderid.setText("");
                lblshowName.setText("");
                JOptionPane.showMessageDialog(rootPane,"Order Declined.");
                model.removeRow(row);
                row=-1;
            } catch (IOException ex) {
                Logger.getLogger(JFramePendingOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeclineActionPerformed

    public void showtabledata()
   {
        Vorder odr = new Vorder(vendorid);
        List<Vorder> orderlist=odr.ReadOrder();
        for (Vorder od:orderlist)
        {
            Object[] rowData = 
            {
                od.getOrderid(),
                od.getOrderdate(),
                od.getOrderprice(),
                od.getOrderservice(),
                od.getItemname(),
                od.getOrderstatus(),
                od.getItemid(),
            };
            if(od.getOrderstatus().equals("pending"))
            {
                model.addRow(rowData);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePendingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePendingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePendingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePendingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePendingOrder().setVisible(true);
            }
        });
    }

    private String vendorid;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnDecline;
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblshowName;
    private javax.swing.JLabel lblshoworderid;
    private javax.swing.JTable ordertable;
    // End of variables declaration//GEN-END:variables
}
