/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fos;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class RunnerRegistration extends javax.swing.JFrame 
{
    private DefaultTableModel runnerDetails = new DefaultTableModel();
    private String column [] = {"UserID", "Username", "Gender", "Age", "Email", "Phone Number"};

    

    /**
     * Creates new form RunnerRegistration
     */
    public RunnerRegistration(String adminUserID) 
    {
        initComponents();
        this.adminUserID=adminUserID;
        runnerDetails.setColumnIdentifiers(column);
        loadDetails();
    }
    
    public RunnerRegistration()
    {
        initComponents();
        runnerDetails.setColumnIdentifiers(column);
        loadDetails();
    }
    
    private String adminUserID;
    
    public void loadDetails() 
    {
        Registration rR = new Registration();
        runnerDetails.setRowCount(0); // Clear existing rows

        try 
        {
            List<Runnerprofile> runnerList = rR.readRunner();
            for (Runnerprofile rn : runnerList) 
            {
                Object[] rowData = 
                {
                    rn.getRunnerid(),
                    rn.getRunnername(),
                    rn.getGender(),
                    rn.getAge(),
                    rn.getEmail(),
                    rn.getPhonenum(),
                };
                runnerDetails.addRow(rowData);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public void displayPassword(String runnerid) 
    {
        Registration rR = new Registration();

        try 
        {
            List<User> userList = rR.readUser();

            for (User user : userList) 
            {
                if (runnerid.equals(user.getUserID())) 
                {
                    jTextFieldRPw.setText(user.getPassword());
                    break;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private User getUserForRunnerUserID(String runnerid) 
    {
        Registration rR = new Registration();
        
        try 
        {
            List<User> userList = rR.readUser();

            for (User user : userList) 
            {
                if (user.getUserID().equals(runnerid)) 
                {
                    return user;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldRG = new javax.swing.JTextField();
        jTextFieldRA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonRC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonRE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonRBTHP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonRD = new javax.swing.JButton();
        jTextFieldRID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRUN = new javax.swing.JTextField();
        jTextFieldREm = new javax.swing.JTextField();
        jTextFieldRPw = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldRPN = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableR = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("Runner");

        jLabel4.setText("Password : ");

        jButtonRC.setText("Create");
        jButtonRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRCActionPerformed(evt);
            }
        });

        jLabel5.setText("Gender : ");

        jLabel2.setText("UserID : ");

        jButtonRE.setText("Edit");
        jButtonRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREActionPerformed(evt);
            }
        });

        jLabel3.setText("Username : ");

        jButtonRBTHP.setText("Back To Home Page");
        jButtonRBTHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRBTHPActionPerformed(evt);
            }
        });

        jLabel6.setText("Age : ");

        jButtonRD.setText("Delete");
        jButtonRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRDActionPerformed(evt);
            }
        });

        jLabel7.setText("Email : ");

        jLabel8.setText("Phone Number : ");

        jTableR.setModel(runnerDetails);
        jTableR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableRMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableR);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRC)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRD))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldRID, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jTextFieldRUN, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jTextFieldRPw, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jTextFieldRG, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jTextFieldRA, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jTextFieldREm)
                                    .addComponent(jTextFieldRPN))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(jButtonRBTHP)
                        .addGap(243, 243, 243))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(148, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldRID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldRUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldRPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldREm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldRPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRE)
                    .addComponent(jButtonRD)
                    .addComponent(jButtonRC)
                    .addComponent(jButtonRBTHP))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRBTHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRBTHPActionPerformed
        AdminHomePage hp1 = new AdminHomePage(adminUserID);
        hp1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRBTHPActionPerformed

    private void jButtonRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRCActionPerformed
        String runnerid = jTextFieldRID.getText();
        String runnername = jTextFieldRUN.getText();
        String password = jTextFieldRPw.getText();
        String gender = jTextFieldRG.getText();
        String age = jTextFieldRA.getText();
        String email = jTextFieldREm.getText();
        String phonenum = jTextFieldRPN.getText();
        
        Registration rr = new Registration();
        
        Runnerprofile nR = null;
        try {
            nR = rr.registerRunner(runnerid, runnername, password, gender, age, email, phonenum);
        } catch (IOException ex) {
            Logger.getLogger(RunnerRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object[] rowData = 
        {
            nR.getRunnerid(), 
            nR.getRunnername(),
            nR.getGender(),
            nR.getAge(),
            nR.getEmail(), 
            nR.getPhonenum()
        };
        runnerDetails.addRow(rowData);

        clearTextField();
    }//GEN-LAST:event_jButtonRCActionPerformed

    private void jButtonREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREActionPerformed
        int row = jTableR.getSelectedRow();

        if (row == -1) {
        // No row selected, show an error or return
            return;
        }
        
        String selectedUserID = jTextFieldRID.getText();
        String newGender = jTextFieldRG.getText();
        String newAge = jTextFieldRA.getText();
        String newEmail = jTextFieldREm.getText();
        String newPhonenum = jTextFieldRPN.getText();
        
        Registration er = new Registration();
        
        DefaultTableModel runnerDetails = (DefaultTableModel) jTableR.getModel();
        runnerDetails.setValueAt(newGender, row, 2);
        runnerDetails.setValueAt(newAge, row, 3);
        runnerDetails.setValueAt(newEmail, row, 4);
        runnerDetails.setValueAt(newPhonenum, row, 5);
        
        try {
            er.editRunner(selectedUserID, newGender, newAge, newEmail, newPhonenum);
        }catch (IOException e) {
            e.printStackTrace(); // Handle the exception according to your application's needs
        }
        
        clearTextField();

    }//GEN-LAST:event_jButtonREActionPerformed

    private void jButtonRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRDActionPerformed
        int row = jTableR.getSelectedRow();
        Registration dr = new Registration();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(this, "Please select a row");
        }
        else
        {
            String selectedUserID = String.valueOf(runnerDetails.getValueAt(row, 0));
            
            try 
            {
                dr.deleteRunner(selectedUserID);
            } catch (IOException e) {
                e.printStackTrace(); // Handle the exception according to your application's needs
            }
            
            runnerDetails.removeRow(row);
            clearTextField();
        }

    }//GEN-LAST:event_jButtonRDActionPerformed

    private void jTableRMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRMouseReleased
        int row = jTableR.getSelectedRow();

        String runnerid = String.valueOf(runnerDetails.getValueAt(row,0));
        
        displayPassword(runnerid);
        
        User selectedUser = getUserForRunnerUserID(runnerid);
        
        String runnername = String.valueOf(runnerDetails.getValueAt(row,1));
        String gender = String.valueOf(runnerDetails.getValueAt(row,2));
        String age = String.valueOf(runnerDetails.getValueAt(row,3));
        String email = String.valueOf(runnerDetails.getValueAt(row,4));
        String phonenum = String.valueOf(runnerDetails.getValueAt(row,5));
        
        jTextFieldRID.setText(runnerid);
        jTextFieldRUN.setText(runnername);
        jTextFieldRG.setText(gender);
        jTextFieldRA.setText(age);
        jTextFieldREm.setText(email);
        jTextFieldRPN.setText(phonenum);
    }//GEN-LAST:event_jTableRMouseReleased

    public void clearTextField()
    {
        jTextFieldRID.setText("");
        jTextFieldRUN.setText("");
        jTextFieldRPw.setText("");
        jTextFieldRG.setText("");
        jTextFieldRA.setText("");
        jTextFieldREm.setText("");
        jTextFieldRPN.setText("");
        
        Registration rcr = new Registration();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunnerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunnerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunnerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunnerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunnerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRBTHP;
    private javax.swing.JButton jButtonRC;
    private javax.swing.JButton jButtonRD;
    private javax.swing.JButton jButtonRE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableR;
    private javax.swing.JTextField jTextFieldRA;
    private javax.swing.JTextField jTextFieldREm;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldRID;
    private javax.swing.JTextField jTextFieldRPN;
    private javax.swing.JTextField jTextFieldRPw;
    private javax.swing.JTextField jTextFieldRUN;
    // End of variables declaration//GEN-END:variables
}
